name: mdist-mmidas
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - alsa-lib=1.2.12=h4ab18f5_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - attr=2.5.1=h166bdaf_1
  - binutils=2.40=h4852527_7
  - binutils_impl_linux-64=2.40=ha1999f0_7
  - binutils_linux-64=2.40=hb3c18ed_9
  - blas=2.116=mkl
  - blas-devel=3.9.0=16_linux64_mkl
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.1.0=py312h30efb56_1
  - bzip2=1.0.8=hd590300_5
  - c-compiler=1.7.0=hd590300_1
  - ca-certificates=2024.7.4=hbcca054_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2024.7.4=pyhd8ed1ab_0
  - cffi=1.16.0=py312hf06ca03_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.2.1=py312h8572e83_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.5.39=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.5=3
  - cxx-compiler=1.7.0=h00ab1b0_1
  - cycler=0.12.1=pyhd8ed1ab_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.8.2=py312h7070661_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.6.2=h59595ed_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.15.4=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.53.1=py312h41a817b_0
  - freetype=2.12.1=h267a509_2
  - fsspec=2024.6.1=pyhff2d567_0
  - gcc=12.3.0=h915e2ae_13
  - gcc_impl_linux-64=12.3.0=h58ffeeb_13
  - gcc_linux-64=12.3.0=h9528a6a_9
  - gettext=0.22.5=h59595ed_2
  - gettext-tools=0.22.5=h59595ed_2
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.43=pyhd8ed1ab_0
  - glib=2.80.2=hf974151_0
  - glib-tools=2.80.2=hb6ce0ca_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.5=py312h1d5cde6_1
  - gnutls=3.6.13=h85f3911_1
  - graphite2=1.3.13=h59595ed_1003
  - gst-plugins-base=1.24.4=h9ad1361_0
  - gstreamer=1.24.4=haf2f30d_0
  - gxx=12.3.0=h915e2ae_13
  - gxx_impl_linux-64=12.3.0=h2a574ab_13
  - gxx_linux-64=12.3.0=ha28b414_9
  - h2=4.1.0=pyhd8ed1ab_0
  - harfbuzz=8.5.0=hfac3d4d_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.7=pyhd8ed1ab_0
  - importlib-metadata=8.0.0=pyha770c72_0
  - importlib_metadata=8.0.0=hd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.26.0=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py312h7900ff3_0
  - kernel-headers_linux-64=2.6.32=he073ed8_17
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py312h8572e83_1
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240116.2=cxx17_h59595ed_0
  - libasprintf=0.22.5=h661eb56_2
  - libasprintf-devel=0.22.5=h661eb56_2
  - libblas=3.9.0=16_linux64_mkl
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcap=2.69=h0f662aa_0
  - libcblas=3.9.0=16_linux64_mkl
  - libclang-cpp15=15.0.7=default_h127d8a8_5
  - libclang13=18.1.7=default_h087397f_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.10.1.7=0
  - libcups=2.3.3=h4637d8d_4
  - libcurand=10.3.6.82=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.20=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.3=h59595ed_0
  - libgcc-devel_linux-64=12.3.0=h6b66f73_113
  - libgcc-ng=14.1.0=h77fa898_0
  - libgcrypt=1.11.0=h4ab18f5_0
  - libgettextpo=0.22.5=h59595ed_2
  - libgettextpo-devel=0.22.5=h59595ed_2
  - libgfortran-ng=14.1.0=h69a702a_0
  - libgfortran5=14.1.0=hc5f4f2c_0
  - libglib=2.80.2=hf974151_0
  - libgomp=14.1.0=h77fa898_0
  - libgpg-error=1.50=h4f305b6_0
  - libhwloc=2.11.0=default_h5622ce7_1000
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=16_linux64_mkl
  - liblapacke=3.9.0=16_linux64_mkl
  - libllvm15=15.0.7=hb3ce162_4
  - libllvm18=18.1.7=hb77312f_0
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hd590300_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libogg=1.3.5=h4ab18f5_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.43=h2797004_0
  - libpq=16.3=ha72fbe1_0
  - libprotobuf=4.25.3=h08a7969_0
  - libsanitizer=12.3.0=hb8811af_13
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libstdcxx-devel_linux-64=12.3.0=h6b66f73_113
  - libstdcxx-ng=14.1.0=hc0a3c3a_0
  - libsystemd0=255=h3516f8a_1
  - libtiff=4.6.0=h1dd3fc0_3
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.7.0=h662e7e4_0
  - libxml2=2.12.7=hc051c1a_1
  - libzlib=1.2.13=h4ab18f5_6
  - lightning=2.3.2=pyhd8ed1ab_0
  - lightning-utilities=0.11.3.post0=pyhd8ed1ab_0
  - llvm-openmp=15.0.7=h0cdce71_0
  - lz4-c=1.9.4=hcb278e6_0
  - markupsafe=2.1.5=py312h98912ed_0
  - matplotlib=3.8.4=py312h7900ff3_2
  - matplotlib-base=3.8.4=py312h20ab3a6_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mkl=2022.1.0=h84fe81f_915
  - mkl-devel=2022.1.0=ha770c72_916
  - mkl-include=2022.1.0=h84fe81f_915
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.1=h9458935_1
  - mpg123=1.32.6=h59595ed_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.3.0=hf1915f5_4
  - mysql-libs=8.3.0=hca2cd23_4
  - nccl=2.20.5.1=h3a97aeb_0
  - ncurses=6.5=h59595ed_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nettle=3.6=he412f7d_0
  - networkx=3.3=pyhd8ed1ab_1
  - nspr=4.35=h27087fc_0
  - nss=3.100=hca3bf56_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.3.1=h4ab18f5_1
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.2=py312h1d6d2e6_1
  - parso=0.8.4=pyhd8ed1ab_0
  - pathtools=0.1.2=py_1
  - pcre2=10.43=hcad00b1_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.3.0=py312hdcec9eb_0
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - plotly=5.22.0=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_2
  - prompt-toolkit=3.0.47=pyha770c72_0
  - protobuf=4.25.3=py312h72fbbdf_0
  - psutil=6.0.0=py312h9a8786e_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulseaudio-client=17.0=hb77b528_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pyqt=5.15.9=py312h949fe66_5
  - pyqt5-sip=12.12.2=py312h30efb56_5
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.12.3=hab00c5b_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.12=4_cp312
  - pytorch=2.3.1=py3.12_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-lightning=2.3.3=pyhd8ed1ab_0
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py312h98912ed_1
  - pyzmq=26.0.3=py312h8fd38d8_0
  - qt-main=5.15.8=hc9dc06e_21
  - readline=8.2=h8228510_1
  - requests=2.32.3=pyhd8ed1ab_0
  - sentry-sdk=2.8.0=pyhd8ed1ab_0
  - setproctitle=1.3.3=py312h98912ed_0
  - setuptools=70.1.1=pyhd8ed1ab_0
  - sip=6.7.12=py312h30efb56_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.12.1=pypyh2585a3b_103
  - sysroot_linux-64=2.12=he073ed8_17
  - tbb=2021.12.0=h434a139_2
  - tenacity=8.5.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - torchaudio=2.3.1=py312_cu121
  - torchmetrics=1.4.0.post0=pyhd8ed1ab_0
  - torchvision=0.18.1=py312_cu121
  - tornado=6.4.1=py312h9a8786e_0
  - tqdm=4.66.4=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - urllib3=2.2.2=pyhd8ed1ab_1
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - xcb-util=0.4.0=hd590300_1
  - xcb-util-image=0.4.0=h8ee46fc_1
  - xcb-util-keysyms=0.4.0=h8ee46fc_1
  - xcb-util-renderutil=0.3.9=hd590300_1
  - xcb-util-wm=0.4.1=h8ee46fc_1
  - xkeyboard-config=2.42=h4ab18f5_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.5=h75354e8_4
  - zipp=3.19.2=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.22.0=py312h5b18bf6_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - absl-py==2.1.0
      - anndata==0.10.8
      - anyio==4.4.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - array-api-compat==1.7.1
      - arrow==1.3.0
      - async-lru==2.0.4
      - attrs==23.2.0
      - babel==2.15.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - defusedxml==0.7.1
      - fastjsonschema==2.20.0
      - feather-format==0.4.1
      - flatten-json==0.1.14
      - fqdn==1.5.1
      - grpcio==1.64.1
      - h11==0.14.0
      - h5py==3.11.0
      - hdf5plugin==4.4.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - isoduration==20.11.0
      - isort==5.13.2
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.2
      - legacy-api-wrap==1.4
      - llvmlite==0.43.0
      - markdown==3.6
      - mistune==3.0.2
      - natsort==8.4.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - notebook-shim==0.2.4
      - numba==0.60.0
      - numpy==1.26.4
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - patsy==0.5.6
      - prometheus-client==0.20.0
      - pyarrow==16.1.0
      - pynndescent==0.5.13
      - pyrsistent==0.20.0
      - python-json-logger==2.0.7
      - referencing==0.35.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.19.0
      - scanpy==1.10.2
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - seaborn==0.13.2
      - send2trash==1.8.3
      - session-info==1.0.0
      - sniffio==1.3.1
      - soupsieve==2.5
      - statsmodels==0.14.2
      - stdlib-list==0.10.0
      - tensorboard==2.17.0
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.3.0
      - types-python-dateutil==2.9.0.20240316
      - umap-learn==0.5.6
      - uri-template==1.3.0
      - wandb==0.17.4
      - webcolors==24.6.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.3
prefix: /home/hilal.mufti/miniforge3/envs/mdist-mmidas
